<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="griffon.core.i18n.NoSuchMessageExceptionSpec" tests="2" skipped="0" failures="1" errors="0" timestamp="2016-01-16T22:23:33" hostname="testing-gce-deeed465-4600-477e-9ad3-7a5ac8a2250f.c.eco-emissary-99515.internal" time="0.017">
  <properties/>
  <testcase name="Exercise constructor with errors" classname="griffon.core.i18n.NoSuchMessageExceptionSpec" time="0.017">
    <failure message="Expected exception of type 'java.lang.NullPointerException', but got 'groovy.lang.GroovyRuntimeException'" type="org.spockframework.runtime.WrongExceptionThrownError">Expected exception of type 'java.lang.NullPointerException', but got 'groovy.lang.GroovyRuntimeException'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:79)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:66)
	at griffon.core.i18n.NoSuchMessageExceptionSpec.Exercise constructor with errors(NoSuchMessageExceptionSpec.groovy:26)
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method griffon.core.i18n.NoSuchMessageException#&lt;init&gt;.
Cannot resolve which method to invoke for [class java.lang.String, null] due to overlapping prototypes between:
	[class java.lang.String, class java.util.Locale]
	[class java.lang.String, class java.lang.Throwable]
	at griffon.core.i18n.NoSuchMessageExceptionSpec.Exercise constructor with errors(NoSuchMessageExceptionSpec.groovy:23)
</failure>
  </testcase>
  <testcase name="Successfully create exception" classname="griffon.core.i18n.NoSuchMessageExceptionSpec" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
